### ISSUE TITLE
PhatLoots generated an exception - java.lang.NumberFormatException

### ISSUE THREAD

**Issue by mibby** [Codisimus/PhatLoots#11]
@Codisimus 

Vanilla configs for lores.yml, enchantments.yml, and tiers.yml. Updated/downloaded/replaced specifically for build 3.7.4.

Config.yml - http://paste.ubuntu.com/6696124/
Zombie LootTable. - http://paste.ubuntu.com/6696120/
ZombieSpawn LootTable. - http://paste.ubuntu.com/6696121/

```
[Server thread/WARN]: [PhatLoots] Task #80 for PhatLoots v3.7.4 generated an exception
java.lang.NumberFormatException: For input string: "TIERS"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0-ea]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0-ea]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0-ea]
	at com.codisimus.plugins.phatloots.loot.Item.getTieredName(Item.java:804) ~[?:?]
	at com.codisimus.plugins.phatloots.loot.Item.getItem(Item.java:453) ~[?:?]
	at com.codisimus.plugins.phatloots.loot.Item.getLoot(Item.java:196) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoot.rollForLoot(PhatLoot.java:686) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoot.rollForLoot(PhatLoot.java:671) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoot.rollForEquipment(PhatLoot.java:568) ~[?:?]
	at com.codisimus.plugins.phatloots.listeners.MobSpawnListener$1.run(MobSpawnListener.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[spigot.jar:git-Spigot-1227]
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot.jar:git-Spigot-1227]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:583) [spigot.jar:git-Spigot-1227]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1227]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:540) [spigot.jar:git-Spigot-1227]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:446) [spigot.jar:git-Spigot-1227]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1227]
```

**Comment by Codisimus** [comment]
I don't think this has been reproduced in a long time.
