### ISSUE TITLE
Error while enabling

### ISSUE THREAD

**Issue by FlyingPikachu** [Codisimus/PhatLoots#16]
[15:24:55] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-952179b-e87122e (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

>Thanks for the update! Server has sufficient memory; all other plugins load.

[15:25:29] [Server thread/ERROR]: Error occurred while enabling PhatLoots v4.0.0 (Is it up to date?)
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapCharBuffer.<init>(Unknown Source) ~[?:1.8.0_25]
	at java.nio.CharBuffer.allocate(Unknown Source) ~[?:1.8.0_25]
	at java.nio.charset.CharsetDecoder.decode(Unknown Source) ~[?:1.8.0_25]
	at com.codisimus.plugins.phatloots.PhatLoots.isValidUTF8(PhatLoots.java:578) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoots.loadConfig(PhatLoots.java:559) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoots.load(PhatLoots.java:302) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoots.onEnable(PhatLoots.java:176) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.citizensnpcs.util.NMS.loadPlugins(NMS.java:277) [citizens-2.0.14-SNAPSHOT.jar:?]
	at net.citizensnpcs.Citizens.enableSubPlugins(Citizens.java:142) [citizens-2.0.14-SNAPSHOT.jar:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:288) [citizens-2.0.14-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by FlyingPikachu** [comment]
> Still occurs in PhatLoots v4.1.0 on Spigot 1.8.3

[16:18:34] [Server thread/ERROR]: Error occurred while enabling PhatLoots v4.1.0 (Is it up to date?)
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapCharBuffer.<init>(Unknown Source) ~[?:1.8.0_25]
	at java.nio.CharBuffer.allocate(Unknown Source) ~[?:1.8.0_25]
	at java.nio.charset.CharsetDecoder.decode(Unknown Source) ~[?:1.8.0_25]
	at com.codisimus.plugins.phatloots.PhatLoots.isValidUTF8(PhatLoots.java:540) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoots.loadConfig(PhatLoots.java:521) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoots.load(PhatLoots.java:277) ~[?:?]
	at com.codisimus.plugins.phatloots.PhatLoots.onEnable(PhatLoots.java:157) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at net.citizensnpcs.util.NMS.loadPlugins(NMS.java:355) [citizens-2.0.15-SNAPSHOT.jar:?]
	at net.citizensnpcs.Citizens.enableSubPlugins(Citizens.java:142) [citizens-2.0.15-SNAPSHOT.jar:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:288) [citizens-2.0.15-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit.jar:git-Spigot-c136710-350cb99]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by Codisimus** [comment]
Can you upload your save files? I can't imagine why they would grow to be so large.

**Comment by FlyingPikachu** [comment]
Well, I just looked at the PhatLoots folder is 8GB+. Looks like book information in LootTables are being saved "too much". Here's what I mean (smallest file I could find, sorry!):

https://dl.dropboxusercontent.com/u/72509980/Story8.yml

**Comment by Codisimus** [comment]
Ah, this was caused by a CraftBukkit bug which duplicated book pages. It
has since been fixed. You will have to manually fix it but it won't happen
again.

**Comment by FlyingPikachu** [comment]
Sweet, thanks!
