### ISSUE TITLE
PhatLoots does not start when used with Mythicdrops

### ISSUE THREAD

**Issue by p4ste** [Codisimus/PhatLoots#24]
When starting with Mythicdrops also installed, I get the following error:

`Error occurred while enabling PhatLoots v4.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/nunnerycode/bukkit/mythicdrops/tiers/TierMap
        at com.codisimus.plugins.phatloots.loot.MythicDropsItem.instantiateTierList(MythicDropsItem.java:296) ~[?:?]
        at com.codisimus.plugins.phatloots.loot.MythicDropsItem.<clinit>(MythicDropsItem.java:39) ~[?:?]
        at com.codisimus.plugins.phatloots.PhatLoots.onEnable(PhatLoots.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.ClassNotFoundException: net.nunnerycode.bukkit.mythicdrops.tiers.TierMap
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
        ... 14 more`

**Comment by Codisimus** [comment]
duplicate of #21
