### ISSUE TITLE
Failed to load (name).yml

### ISSUE THREAD

**Issue by iDrmzIt** [Codisimus/PhatLoots#30]
I updated from 1.8 (4.1) to 1.9 (4.2.2) and I find that my RareCrate.yml and CommonCrate.yml are suddenly not working. They work just fine with the old PhatLoot on 1.8. 

Note: The beginning mentions an outdated config, deleting it does not fix the issue.

[00:10:53] [Server thread/WARN]: [PhatLoots] Your config.yml file is outdated! To get the most out of this plugin please (re)move the old file so a new one can be generated.
[00:10:53] [Server thread/ERROR]: Could not call constructor 'public com.codisimus.plugins.phatloots.PhatLoot(java.util.Map)' of class com.codisimus.plugins.phatloots.PhatLoot for deserialization
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_65]
    at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_65]
    at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.PhatLoot.clean(Unknown Source) ~[?:?]
    at com.codisimus.plugins.phatloots.PhatLoot.loadLootTimes(Unknown Source) ~[?:?]
    at com.codisimus.plugins.phatloots.PhatLoot.<init>(Unknown Source) ~[?:?]
    at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_65]
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:96) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:133) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at com.codisimus.plugins.phatloots.PhatLoots.loadConfig(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.PhatLoots.load(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.PhatLoots.rl(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.LootCommand.reload(Unknown Source) [PhatLoots.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.handleCommand(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.onCommand(Unknown Source) [PhatLoots.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[00:10:53] [Server thread/ERROR]: [PhatLoots] Failed to load CommonCrate.yml
java.util.NoSuchElementException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_65]
    at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.PhatLoots.load(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.PhatLoots.rl(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.LootCommand.reload(Unknown Source) [PhatLoots.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.handleCommand(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.onCommand(Unknown Source) [PhatLoots.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[00:10:53] [Server thread/ERROR]: Could not call constructor 'public com.codisimus.plugins.phatloots.PhatLoot(java.util.Map)' of class com.codisimus.plugins.phatloots.PhatLoot for deserialization
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_65]
    at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_65]
    at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.PhatLoot.clean(Unknown Source) ~[?:?]
    at com.codisimus.plugins.phatloots.PhatLoot.loadLootTimes(Unknown Source) ~[?:?]
    at com.codisimus.plugins.phatloots.PhatLoot.<init>(Unknown Source) ~[?:?]
    at sun.reflect.GeneratedConstructorAccessor52.newInstance(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_65]
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaCtor(ConfigurationSerialization.java:96) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:133) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at com.codisimus.plugins.phatloots.PhatLoots.loadConfig(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.PhatLoots.load(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.PhatLoots.rl(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.LootCommand.reload(Unknown Source) [PhatLoots.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.handleCommand(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.onCommand(Unknown Source) [PhatLoots.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[00:10:53] [Server thread/ERROR]: [PhatLoots] Failed to load RareCrate.yml
java.util.NoSuchElementException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_65]
    at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.PhatLoots.load(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.PhatLoots.rl(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.LootCommand.reload(Unknown Source) [PhatLoots.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.handleCommand(Unknown Source) [PhatLoots.jar:?]
    at com.codisimus.plugins.phatloots.commands.CommandHandler.onCommand(Unknown Source) [PhatLoots.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-Build3182016.jar:git-Spigot-095e59a-2bfda1f]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[00:10:53] [Server thread/INFO]: [PhatLoots] PhatLoots reloaded
[00:11:37] [Server thread/INFO]: iDrmzIt issued server command: /loot CommonCrate

**Comment by Codisimus** [comment]
Can you show me the yml files? Perhaps as a pastebin so that the formatting stays in tact.

**Comment by iDrmzIt** [comment]
Sure, one moment

**Comment by iDrmzIt** [comment]
Here. http://pastebin.com/Dmxm6kTF
Contains both files

**Comment by Codisimus** [comment]
I copied them over into two separate files and they seemed to load fine for me. I didn't see any errors. You can try the attached file below, The colors have been lost during the copy paste but we can worry about that later once we get the files working.

[LootTables.zip](https://github.com/Codisimus/PhatLoots/files/190512/LootTables.zip)
![commoncrate](https://cloud.githubusercontent.com/assets/680766/14060535/f3085f32-f33d-11e5-82ae-69d3beb430f3.jpg)
![rarecrate](https://cloud.githubusercontent.com/assets/680766/14060537/0a142e40-f33e-11e5-9314-95b985cfab3b.jpg)

**Comment by iDrmzIt** [comment]
i don't understand why it would be broken though

**Comment by Codisimus** [comment]
That's what I was wondering. It didnt seem broken when I tried those two files.

**Comment by iDrmzIt** [comment]
Maybe it's my computer

**Comment by iDrmzIt** [comment]
Took those files, used them in my test server, same error.

**Comment by Codisimus** [comment]
It looks like it is actually the LootTime files which are causing it to crash. Can you send me a copy of those files? That is the files within the LootTimes folder. A simple fix would be to (re)move those two files but if you show them to me then I could help to prevent this from happening again in the future.

**Comment by iDrmzIt** [comment]
Files:


[LootTimes.zip](https://github.com/Codisimus/PhatLoots/files/191046/LootTimes.zip)

**Comment by Codisimus** [comment]
I cannot determine how the files ended up this way but if you remove them it will fix the issue. Let me know if you require any further help.
