### ISSUE TITLE
Phatloots not saving loot tables to yml

### ISSUE THREAD

**Issue by marshmellion** [Codisimus/PhatLoots#34]
Heyy,
 I am using your plugin and my server sort of revolves around it however after many weeks setting up the server i start to add loots and I realized they are not saving to the config for reasons unknown. my council says this **Could not pass event InventoryCloseEvent to PhatLoots v4.1.0**

please help otherwise i just spent 450 and many hours making my server only to have it fail. I will pay more if i need to to have you simply fix this and help me. 

(also its 4.0.1 because not everything is 1.9 yet.) if you can help that would be awesome)[that is if you even read emails anymore you've been reclusive and impossible to get a hold of]

08.04 01:21:13 [Server] INFO CONSOLE issued server command: /list 08.04 01:19:04 [Server] INFO King: [AFK][AncientDragon]MoonBlossems 08.04 01:19:04 [Server] INFO CONSOLE issued server command: /list 08.04 01:18:40 [Server] INFO All active mobs have been saved! 08.04 01:18:40 [Server] INFO Saving all active Mythic Mobs... 08.04 01:16:54 [Server] INFO King: [AncientDragon]MoonBlossems 08.04 01:16:54 [Server] INFO CONSOLE issued server command: /list 08.04 01:16:00 [Server] INFO Backpacks have been saved. 08.04 01:16:00 [Server] INFO Saving 4 backpack(s)... 08.04 01:15:59 [Server] INFO World saved. 08.04 01:15:59 [Server] INFO Saving... 08.04 01:15:59 [Server] INFO Saving is already turned on. 08.04 01:15:59 [Multicraft] Auto-saving world... 08.04 01:14:45 [Server] INFO King: [AncientDragon]MoonBlossems 08.04 01:14:45 [Server] INFO CONSOLE issued server command: /list 08.04 01:14:45 [Multicraft] Skipped 41 lines due to rate limit (30/s) 08.04 01:12:52 [Server] INFO at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:35) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:850) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:173) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null 08.04 01:12:52 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45] 08.04 01:12:52 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1411) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:851) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f] 08.04 01:12:52 [Server] INFO org.bukkit.event.EventException 08.04 01:12:52 [Server] ERROR Could not pass event InventoryCloseEvent to PhatLoots v4.1.0 08.04 01:12:40 [Server] INFO _StarGazer_ issued server command: /loot gui

**Comment by Codisimus** [comment]
Hi @marshmellion,

I will look into this after work today unless I have time during lunch. I want to pin point the problem so in the meantime, if you could send your save files (if any) then I can take a look at them later. it does look like the error is caused by a skull with it's owner set to 'null' as you highlighted. So let's see if we can get that fixed and make sure it doesn't happen again. If I have to create a new build it looks like you are running Spigot 1.8.8 is that correct?

**Comment by marshmellion** [comment]
yes i am running spigot 1.8.8, it also does seem to be the skull as i have
done some tests. It seems to be a problem when you try to use custom player
skulls inside loot tables.
Ei: microblocks.
anyskill that isnt a default minecraft skull is counted as null.

**Comment by marshmellion** [comment]
i have tried to use a command to spawn the heads in and that didnt work
either. (command Blocks)
I also tried a plugin i have to get the skulls(though i dont think the
plugin is a problem)
https://www.spigotmc.org/resources/head-database-1300-heads.14280/

**Comment by Codisimus** [comment]
Unfortunately, this is a known bug in Spigot. There are several tickets that were created for it including [SPIGOT-583](https://hub.spigotmc.org/jira/browse/SPIGOT-583), [SPIGOT-1066](https://hub.spigotmc.org/jira/browse/SPIGOT-1066), [SPIGOT-1496](https://hub.spigotmc.org/jira/browse/SPIGOT-1496), [SPIGOT-1465](https://hub.spigotmc.org/jira/browse/SPIGOT-1465), and [SPIGOT-1494](https://hub.spigotmc.org/jira/browse/SPIGOT-1494). It looks like the Spigot team has fixed it but it might only be fixed in Spigot 1.9+

**Comment by marshmellion** [comment]
well that sucks. well thanks for responding.

**Comment by marshmellion** [comment]
there may be some possible workarounds in these two threads. If you could
take a look that would be cool.

https://www.spigotmc.org/threads/serialize-skulls-with-no-owner.102833/
https://www.spigotmc.org/threads/skull-setowner-uuid.25634/

**Comment by Codisimus** [comment]
It might be kinda hacky but I think from those posts I can come up with something that will prevent the errors in 1.8

**Comment by Codisimus** [comment]
I have released a fix which can be a found at https://github.com/Codisimus/PhatLoots/releases/tag/v4.1.1

**Comment by marshmellion** [comment]
Thanks
