### ISSUE TITLE
Phatloot is not working properly

### ISSUE THREAD

**Issue by ZeroThinking420** [Codisimus/PhatLoots#42]
Hey there, we have used phatloot for a long time now and think its a great plugin, currently we are in the process of updating to 1.9.2, I had no problems with downloading Phatloot and getting it to run however for some reason it is not showing me the Phatloot contents of chest properly, it flashes in the chest when its first opened but then disappears within a few split seconds. It seems as though dispensers and droppers still work fine, just not the chest (normal, trap or ender). Any Ideas on what I should do to try fix this problem?

The error below appears when I attempt to open the Phatloot chest.

`[04:49:42 ERROR]: Could not pass event PlayerInteractEvent to PhatLoots v4.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.2.jar:git-Spigo
t-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHEST_OPEN
        at com.codisimus.plugins.phatloots.PhatLootChest.openInventory(PhatLootChest.java:525) ~[?:?]
        at com.codisimus.plugins.phatloots.PhatLoot.rollForChestLoot(PhatLoot.java:422) ~[?:?]
        at com.codisimus.plugins.phatloots.PhatLootsAPI.loot(PhatLootsAPI.java:126) ~[?:?]
        at com.codisimus.plugins.phatloots.listeners.PhatLootsListener.onPlayerInteract(PhatLootsListener.java:50) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        ... 17 more
[04:49:42 ERROR]: Could not pass event InventoryCloseEvent to PhatLoots v4.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:871) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1628) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:739) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.EntityPlayer.openContainer(EntityPlayer.java:697) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.BlockChest.interact(SourceFile:340) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:515) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchFieldError: CHEST_CLOSE
        at com.codisimus.plugins.phatloots.PhatLootChest.closeInventory(PhatLootChest.java:601) ~[?:?]
        at com.codisimus.plugins.phatloots.listeners.PhatLootsListener.onPlayerCloseChest(PhatLootsListener.java:70) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-f972b36-b103841]
        ... 21 more
`

**Comment by tara81** [comment]
try the latest version.. your still on a 1.8 version.. click download and get 4.2.3

**Comment by ZeroThinking420** [comment]
Thank you tara81, lol i don't know why i did't try this first. Cheers :D
