### ISSUE TITLE
Error occurred while enabling PhatLoots v4.1.0 (Is it up to date?)

### ISSUE THREAD

**Issue by JonCup** [Codisimus/PhatLoots#46]
I'm running MythicDrops version 4.0.9-6ed75f4

`[18:49:27 ERROR]: Error occurred while enabling PhatLoots v4.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/nunnerycode/bukkit/mythicdrops/tiers/TierMap
        at com.codisimus.plugins.phatloots.loot.MythicDropsItem.instantiateTierList(MythicDropsItem.java:296) ~[?:?]
        at com.codisimus.plugins.phatloots.loot.MythicDropsItem.<clinit>(MythicDropsItem.java:39) ~[?:?]
        at com.codisimus.plugins.phatloots.PhatLoots.onEnable(PhatLoots.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ClassNotFoundException: net.nunnerycode.bukkit.mythicdrops.tiers.TierMap
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72-internal]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72-internal]
        ... 14 more`

**Comment by JonCup** [comment]
sorry, this is fixed in 4.23 at http://codisimus.com/phatloots

**Comment by JonCup** [comment]
sorry, this is fixed in 4.23 at http://codisimus.com/phatloots
