### ISSUE TITLE
Loot link Error?

### ISSUE THREAD

**Issue by Nightshade73** [Codisimus/PhatLoots#86]
Having a problem I cant seem to resolve. Loot linking chests isnt working properly;

`[20:07:05] [Server thread/INFO]: Nightshade73 issued server command: /loot link Ammo2
[20:07:05] [Server thread/ERROR]: [PhatLoots] Error occured when executing command /loot link
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.codisimus.plugins.phatloots.commands.CommandHandler.handleCommand(Unknown Source) [PhatLoots.jar:?]
	at com.codisimus.plugins.phatloots.commands.CommandHandler.onCommand(Unknown Source) [PhatLoots.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Spigot.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-7754231-94b0980]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-7754231-94b0980]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at com.codisimus.plugins.phatloots.PhatLoot.saveChests(Unknown Source) ~[?:?]
	at com.codisimus.plugins.phatloots.commands.LootCommand.link(Unknown Source) ~[?:?]
	... 22 more`

It is occurring when I use the /loot link command, Which usually works perfectly but has recently started to.. well not work.

**Comment by RiCkYB-667** [comment]
Yup, same here on Spigot 1.12.1.
I started searching for alternatives as this resource seems to be abandoned...

**Comment by Nightshade73** [comment]
I still have hope, 
Mostly because this plugin was my alternative...

Every chest in my world linked with Gear1-4 just got wipped...
and I have a city map so... fuq me,

**Comment by Nightshade73** [comment]
For now cuz I still have not found a suitable replacement. ill wait on an update to fix. I just backedup all my plugin files so I can just Paste it back if it breaks again

**Comment by RiCkYB-667** [comment]
Yeah, well an other alternative is to find someone who can code, and ask him/her to make a clone of this... All the raw information is here, just need someone who can figure out what to do with it :)
