### ISSUE TITLE
autolink

### ISSUE THREAD

**Issue by justinbea** [Codisimus/PhatLoots#89]
i have in /plugins/phatloot/chest/Normal.txt the file with the loot that have to be in the chests, but when i use auto link to link all of the chests in the map it wont link and give this error and dont know what i do wrong

`AutoLink:
    all:
        Chest: Normal`

`Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'string', line 11, column 1:
LootBags: false
^
expected <block end>, but found BlockMappingStart
in 'string', line 69, column 5:
all:
^
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:571) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[spigot.jar:git-Spigot-2086bb0-d0a3620]
... 29 more`

**Comment by justinbea** [comment]
thread closed not even an reaction lol -rep
